spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sumx0816/resource
          username: s_m_x_1234@qq.com
          password: Su198298
          default-label: master
server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
